# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-01 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20190102_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
